name: Delete Deployment Environment

on:
  push:
    branches:
      - 'master'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2.2.3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          environment: ajikan-database
