name: Deploy to digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment:
      name: ajikan-database
      url: https://timagribanov.com/ajikan-database
    
    steps:
      - name: chekout repo
        uses: actions/checkout@v3
      - name: show repo contents
        run: ls -al
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      # - name: workaround for esbuild
      #   run: cd frontend; npm cache clean -f
      - name: show the contents of package.json
        run: cat package.json
      - name: install dependencies
        run: cd frontend; npm install
      - name: build frontend
        run: cd frontend; npm run build
      - name: move frontend built to backend
        run: mv frontend/dist backend
      - name: rename the frontend built
        run: cd backend; mv dist build
      - name: Install SHH-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: deploy
        run: rsycn -ar . ${{ secrets.USER }}@${{ secrets.IP }}:${{ secrets.PATH }}