name: Deploy to Digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Chekout frontend folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: frontend

      - name: Show repo contents
        run: ls -alR
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: cd frontend; npm install
      
      - name: Build frontend
        run: cd frontend; npm run build
      
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: frontend/dist
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ajikan-database
      url: https://timagribanov.com/ajikan-database
    
    steps:
      - name: Chekout backend folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build

      - name: Install SHH-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
     
      - name: deploy
        run: rsycn -ar . ${{ secrets.USER }}@${{ secrets.IP }}:${{ secrets.PATH }}