name: Deploy to digital Ocean

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: chekout repo
        uses: actions/checkout@v2.3.4
      - name: show repo contents
        run: ls -al
      - name: go to frontend directory
        run: cd frontend
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: install dependencies
        uses: bahmutov/npm-install@v1
      - name: build frontend
        run: cd frontend; npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
    
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: ajikan-database
      url: https://timagribanov.com/ajikan-database

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist
      - name: move frontend built to backend
        run: mv dist ../backend
      - name: rename the frontend built
        run: cd ../backend; mv dist build
      - name: Install SHH-key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: deploy
        run: rsycn -ar . ${{ secrets.USER }}@${{ secrets.IP }}:${{ secrets.PATH }}